server:
  port: 8008
spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/oibsdb?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&UseSSL=true
    url: jdbc:mysql://127.0.0.1:3306/springbootchapter08?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&UseSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:db/schema.sql
  # 配置jpa，会在应用启动时自动创建表
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update